### ISSUE TITLE
Unable to save functions to pickle

### ISSUE THREAD

**Issue by z6Solutions** [microsoft/Trace#5]
When running the examples in "5 Minute Basics" in the docs, everything works fine until I go to save the optimized function to a pickle. I'm given this error:

```PicklingError: Can't pickle <function eq at 0x7d4ab853f600>: it's not the same object as opto.trace.operators.eq```

I've tried creating a brand new conda environment with only `trace` and `autogen` and it still gives the same error.

**Comment by chinganc** [comment]
@z6Solutions  I can recreate the error. We will fix it soon.

**Comment by chinganc** [comment]
@z6Solutions  I pushed a fix to that. Can you try again? Thank you.

**Comment by z6Solutions** [comment]
Still getting an error, but a new one. Now I get `PicklingError: Can't pickle <function strange_sort_list at 0x7b70fc061580>: it's not the same object as __main__.strange_sort_list`

**Comment by chinganc** [comment]
I can reproduce it.

**Comment by chinganc** [comment]
@z6Solutions I think it's fixed this time. Please try again, thanks.

**Comment by z6Solutions** [comment]
Works perfectly - thank you!
